### ISSUE TITLE
Add use of namespaces to classes

### ISSUE THREAD

**Issue by Limych** [BorderCloud/SPARQL#2]
Please add use of namespaces to classes and add autoload block to `composer.json`.

**Comment by Limych** [comment]
For example:

To the begining of each php-file:
```php
namespace BorderCloud\SPARQL;
```

To `composer.json`:
```json
"autoload" : {
	"psr-4" : {
		"BorderCloud\\SPARQL\\" : "."
	}
},
```

**Comment by BorderCloud** [comment]
Thanks, I will merge your modification at the end of this week and I will create a package version 2.0.0.
(I will add, in same time,  Travis to do continuous integration  https://github.com/travis-ci-examples/php/blob/master/.travis.yml )

**Comment by Limych** [comment]
Thank you.

As you want to change major version there are will be best to apply strict PSR2 code style to all files. Basically it concerns the names of functions.

**Comment by BorderCloud** [comment]
Ok I will look the PSR2 code style also.

**Comment by BorderCloud** [comment]
I updated the project. Say me, if you see a problem.
https://packagist.org/packages/bordercloud/sparql#dev-master 

I will test all classes with new unit tests the next week.

**Comment by Limych** [comment]
Yes, I already received a notification from the system.

And I already see new problems.

I would like to draw your attention to the fact that the line `"php" : ">=7.1"` in `composer.json` is very much restricts the use of the library. For example, now I have to write code for PHP 5.3+ and this line will not allow me to use the new version of the library.
In addition, it does not allow you to fully pass the testing in Travis-CI.

I advise you to change that line to `"php" : ">=5.2"`, like lowest PHP version described in your Travis-CI configs.

**Comment by BorderCloud** [comment]
I put 5.3 but I think several functions cannot work in the version 5.
Say me if there is a problem.

**Comment by Limych** [comment]
Thank you.
If it would make a problems, you immediately see it on Travis-CI testing. ;)
