### ISSUE TITLE
Problem when trying to use "group_concat"

### ISSUE THREAD

**Issue by sebspas** [BorderCloud/SPARQL#4]
Hi, I got this error when i try to use group_concat or concat or contains...

Parse error: 
```
        prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
        prefix fn: <https://www.w3.org/TR/xpath-functions-3/>
        
        SELECT ?movieLabel ?date ?runtime (group_concat(?actorLabel;separator="|") as ?actorsL) WHERE {
          ?movie rdfs:label ?movieLabel.
          ?actors rdfs:label ?actorLabel.
          ?movie <http://data.linkedmdb.org/resource/movie/actor> ?actors.
          ?movie <http://data.linkedmdb.org/resource/movie/runtime> ?runtime.
          ?movie <http://purl.org/dc/terms/date> ?date.
          ?movie  <http://purl.org/dc/terms/title> "The Shining".
        }
        group by ?movieLabel ?date ?runtime
```
Encountered "group" at line 5, column 44.
Was expecting one of:
    <IRIref> ...
    <PNAME_NS> ...
    <PNAME_LN> ...
    <VAR1> ...
...

Thanks

**Comment by BorderCloud** [comment]
Can you give me the endpoint SPARQL ?

Thanks

**Comment by sebspas** [comment]
This is the endpoint 
http://data.linkedmdb.org/sparql

**Comment by BorderCloud** [comment]
The error is in the query and not in this lib.
[Error...](http://data.linkedmdb.org/sparql?format=text%2Fhtml&timeout=0&debug=on&query=PREFIX%20fn%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2005%2Fxpath-functions%23%3E%20%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%20%0A%0A%20%20%20%20SELECT%20%3FmovieLabel%20%3Fdate%20%3Fruntime%20(group_concat(%3FactorLabel%3Bseparator%3D%22%7C%22)%20as%20%3FactorsL)%20WHERE%20%7B%0A%20%20%20%20%20%20%3Fmovie%20rdfs%3Alabel%20%3FmovieLabel.%0A%20%20%20%20%20%20%3Factors%20rdfs%3Alabel%20%3FactorLabel.%0A%20%20%20%20%20%20%3Fmovie%20%3Chttp%3A%2F%2Fdata.linkedmdb.org%2Fresource%2Fmovie%2Factor%3E%20%3Factors.%0A%20%20%20%20%20%20%3Fmovie%20%3Chttp%3A%2F%2Fdata.linkedmdb.org%2Fresource%2Fmovie%2Fruntime%3E%20%3Fruntime.%0A%20%20%20%20%20%20%3Fmovie%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fdate%3E%20%3Fdate.%0A%20%20%20%20%20%20%3Fmovie%20%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%3E%20%22The%20Shining%22.%0A%20%20%20%20%7D%0A%20%20%20%20group%20by%20%3FmovieLabel%20%3Fdate%20%3Fruntime)

I think, your database doesn't support group_concat, etc...

**Comment by sebspas** [comment]
Oh ok thanks, sorry i'm quite new in sparql ^^'

Thanks again !
