### ISSUE TITLE
Update PHP requirement to ^7.0

### ISSUE THREAD

**Issue by ramsey** [BorderCloud/SPARQL#5]
The `composer.json` file shows a PHP requirement of `>=5.2`, but since you are using features only in PHP 7 (strict types, etc.), you should update the requirement to `^7.0`. 

Leaving it at `>=5.2` will allow users to install it on PHP 5, but then it won’t work.

**Comment by ramsey** [comment]
Indeed, all the PHP 5.x and HHVM builds on Travis CI are failing, as expected.

**Comment by ramsey** [comment]
It also looks like some of the dev dependencies require PHP 7.1, and there isn’t a build defined for 7.0. If defined, the 7.0 build would also fail.

**Comment by BorderCloud** [comment]
Thanks I changed the version in the composer.json.

**Comment by hashar** [comment]
@BorderCloud the `composer.lock` file is out of date and should be regenerated. That causes composer to complain. The file has:
```
{
    "platform": {
        "php": ">=5.2"
    }
}
```
