### ISSUE TITLE
Allow php 7.0

### ISSUE THREAD

**Issue by hashar** [BorderCloud/SPARQL#6]
MediaWiki minimum php version is 7.0  but the https://www.mediawiki.org/wiki/Extension:LinkedWiki requires 7.1 due to this library.

#5 made the requirement to be >=7.1, but it seems to work fine locally when using 7.0.  Would you consider lowering the version requirement slightly?

**Comment by BorderCloud** [comment]
It's done ;-)

**Comment by hashar** [comment]
That solved it apparently :]
