### ISSUE TITLE
Write a regular expression to to identify the good protocol

### ISSUE THREAD

**Issue by BorderCloud** [BorderCloud/SPARQL#8]
This code is not sufficient to identify without error a query for the protocol "update" or "select".

In SparqlClient.php :
```
   if (preg_match("/(INSERT|DELETE|CLEAR|LOAD)/i", $q)) {
                    $response = $this->queryUpdate($q);
                } else {
                    $response = $this->queryRead($q);
                }
```
Somebody can improve this regular expression ?

**Comment by suleiManiac** [comment]
hello @BorderCloud , I'm not sure I understand the issue. Do you want the regex to check if the query starts with "UPDATE" or "SELECT"?

**Comment by BorderCloud** [comment]
@suleiManiac Unfortunately, it would be too simple.

A update query can start by INSERT, DELETE, CLEAR, etc but also by PREFIX and it can contain also SELECT.

You can find examples of queries in this doc:
https://www.w3.org/TR/sparql11-update
